### ISSUE TITLE
Интегрировать базу данных с бэкендом

### ISSUE THREAD

**Issue by newu2012** [BornToCodeStudio/BornToCode_Project#41]
```[Задачи]
### Tasks
- [x] Исправить допущенные в первой версии схемы бд ошибки
- [x] Сделать модели на все базовые сущности
- [x] Провести интеграцию бэкенда с бд, сохранять строку подключения
```
