### ISSUE TITLE
Сделать переход в профиль создателя задачи с главной страницы

### ISSUE THREAD

**Issue by MaxUfimtsev** [BornToCodeStudio/BornToCode_Project#72]
```[tasklist]
### Tasks
- [ ] Сделать структуру страницы
- [ ] Сделать список задач
- [ ] Сделать переход в профиль создателя задачи с главной страницы
```
